# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-09 20:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0002_auto_20170809_1851'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventory',
            name='death',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='inventory',
            name='food_warning',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='inventory',
            name='happening',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='inventory',
            name='landmark',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
