# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-09 21:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0004_auto_20170809_2127'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventory',
            name='death',
            field=models.TextField(blank=True, max_length=5000, null=True),
        ),
    ]
