# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-09 22:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0005_auto_20170809_2131'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventory',
            name='death',
            field=models.TextField(blank=True, default='', max_length=5000, null=True),
        ),
        migrations.AlterField(
            model_name='inventory',
            name='food_warning',
            field=models.CharField(blank=True, default='', max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='inventory',
            name='happening',
            field=models.CharField(blank=True, default='', max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='inventory',
            name='landmark',
            field=models.CharField(blank=True, default='', max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='inventory',
            name='play_message',
            field=models.CharField(blank=True, default='', max_length=500, null=True),
        ),
    ]
