# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-09 22:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0006_auto_20170809_2245'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventory',
            name='find',
            field=models.CharField(blank=True, default='', max_length=500, null=True),
        ),
    ]
