# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-10 20:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0007_inventory_find'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='status',
            field=models.CharField(default='active', max_length=200),
        ),
    ]
