# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-11 21:34
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0009_auto_20170810_2100'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='game',
            name='inventory',
        ),
        migrations.RemoveField(
            model_name='game',
            name='user',
        ),
        migrations.DeleteModel(
            name='Game',
        ),
    ]
